#!/usr/bin/env python3
"""
Fix duplicate title tags flagged by SEMrush Site Audit.

Workflow:
  1. Fetch all /rules URLs with duplicate titles from SEMrush (issue #13)
  2. Map URLs to rule.mdx file paths in this repo
  3. Read the current title from each file's frontmatter
  4. Group files that share the same title value
  5. For each duplicate group: generate distinct replacement titles via OpenAI
  6. Write updated titles back to frontmatter (only the title line changes)
  7. Create a GitHub PR with an old->new mapping table

Required env vars:
    SEMRUSH_API_KEY     - SEMrush API key
    SEMRUSH_PROJECT_ID  - SEMrush project ID for ssw.com.au
    OPENAI_API_KEY      - OpenAI API key

Optional env vars / flags:
    --dry-run           - Print what would change; do not write files or create PR
    --skip-pr           - Write files but do not create a PR
    --limit N           - Process at most N groups (for testing)
    --urls-file PATH    - Read URLs from a file instead of calling SEMrush API
    --list-issues       - Print all SEMrush issue IDs in the latest snapshot and exit
"""

import argparse
import os
import sys
from collections import defaultdict

# Ensure the scripts/semrush directory is importable regardless of cwd
sys.path.insert(0, os.path.dirname(__file__))

from semrush_client import client_from_env
from map_urls_to_files import map_urls_to_files
from fix_duplicate_meta import read_frontmatter_fields, update_title
from generate_title import generate_titles
import github_pr


REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))

TITLE_BRANCH_NAME = github_pr.TITLE_BRANCH_NAME
TITLE_PR_TITLE    = github_pr.TITLE_PR_TITLE

_COMMIT_MSG = (
    "fix(seo): replace duplicate title tags [SEMrush audit]\n\n"
    "Automatically generated by scripts/semrush/run_duplicate_title_fix.py."
)

_PR_BODY_HEADER = """\
## Summary

This PR was generated automatically by the SEMrush duplicate title tag fixer \
(`scripts/semrush/run_duplicate_title_fix.py`).

### What changed

- Only `title` frontmatter fields were updated
- Only `/rules` pages flagged by SEMrush Site Audit (duplicate title tags, issue #13) were processed
- Page body content, seoDescription, and all other frontmatter fields are **unchanged**

### How titles were generated

1. SEMrush Site Audit identified pages sharing identical `title` values
2. Each duplicate group was sent to OpenAI (`gpt-4o-mini`) in one request
3. The model returned distinct replacement titles; validated for uniqueness and length

### Title changes

| File | Old title | New title |
|------|-----------|-----------|
"""

_PR_BODY_FOOTER = """\

### Before merging

- [ ] Review each changed title for accuracy and tone
- [ ] Run frontmatter validation on changed files:
  ```
  cd scripts/frontmatter-validator && npm install
  node frontmatter-validator.js '<comma-separated file paths>'
  ```
- [ ] Edit any unsatisfactory titles directly on this branch

> **Human review is required before merge.**
"""


def _build_pr_body(mappings: list[tuple[str, str, str]]) -> str:
    """
    Build the full PR body.
    mappings: list of (rel_file_path, old_title, new_title)
    """
    rows = "\n".join(
        f"| `{rel}` | {old} | {new} |"
        for rel, old, new in mappings
    )
    return _PR_BODY_HEADER + rows + "\n" + _PR_BODY_FOOTER


def _parse_args():
    parser = argparse.ArgumentParser(description="Fix duplicate SEMrush title tags")
    parser.add_argument("--dry-run", action="store_true",
                        help="Print changes without writing files or creating a PR")
    parser.add_argument("--skip-pr", action="store_true",
                        help="Write files but skip PR creation")
    parser.add_argument("--limit", type=int, default=None,
                        help="Process at most N duplicate groups")
    parser.add_argument("--urls-file", type=str, default=None,
                        help="Read URLs from this file instead of calling SEMrush API")
    parser.add_argument("--list-issues", action="store_true",
                        help="List all SEMrush issue IDs in the snapshot and exit")
    return parser.parse_args()


def main():
    args = _parse_args()

    # ── List-issues diagnostic ────────────────────────────────────────────────
    if args.list_issues:
        client = client_from_env()
        issues = client.list_issues()
        print(f"Found {len(issues)} issue type(s) in snapshot:")
        for issue in issues:
            print(f"  id={issue.get('issue_id')}  total={issue.get('total')}  "
                  f"name={issue.get('name') or issue.get('issue_name') or '(unknown)'}")
        return

    # ── Fetch URLs ────────────────────────────────────────────────────────────
    if args.urls_file:
        print(f"[main] Reading URLs from: {args.urls_file}")
        with open(args.urls_file, "r", encoding="utf-8") as f:
            urls = [line.strip() for line in f if line.strip() and not line.startswith("#")]
        print(f"[main] Loaded {len(urls)} URL(s) from file")
    else:
        client = client_from_env()
        urls = client.get_duplicate_title_pages()

    if not urls:
        print("[main] No duplicate-title URLs found — nothing to do")
        return

    # ── Duplicate PR guard (before any file writes) ───────────────────────────
    if not args.dry_run and not args.skip_pr:
        existing = github_pr.check_open_pr(REPO_ROOT, TITLE_BRANCH_NAME)
        if existing:
            print(
                f"[main] An open PR already exists for {TITLE_BRANCH_NAME!r}: {existing}\n"
                f"[main] Close or merge it before re-running. Aborting."
            )
            sys.exit(1)

    # ── Map URLs to files ─────────────────────────────────────────────────────
    url_to_file = map_urls_to_files(urls, REPO_ROOT)
    if not url_to_file:
        print("[main] No /rules URLs mapped to files — nothing to do")
        return

    # ── Read frontmatter and group by current title ───────────────────────────
    print(f"[main] Reading frontmatter for {len(url_to_file)} file(s)...")
    groups: dict[str, list[dict]] = defaultdict(list)
    skipped = 0

    for url, file_path in url_to_file.items():
        fields = read_frontmatter_fields(file_path)
        if not fields:
            skipped += 1
            continue
        title = fields.get("title")
        if not title:
            print(f"  [main] No title in frontmatter, skipping: {file_path}")
            skipped += 1
            continue
        groups[title].append({
            "file_path": file_path,
            "title": title,
            "seoDescription": fields.get("seoDescription"),
            "_content": fields.get("_content", ""),
        })

    # All mapped files are flagged by SEMrush — process every group regardless of
    # size. A group of 1 means the duplicate is a non-rules page (already skipped
    # by map_urls_to_files), but the rules file still needs a new unique title.
    all_groups = dict(groups)
    print(
        f"[main] {len(all_groups)} title group(s) to process "
        f"({sum(1 for p in all_groups.values() if len(p) >= 2)} with internal duplicates, "
        f"{skipped} file(s) skipped)"
    )

    if not all_groups:
        print("[main] No files to process — nothing to do")
        return

    # ── Process each group ────────────────────────────────────────────────────
    changed_files: list[str] = []
    mappings: list[tuple[str, str, str]] = []  # (rel_path, old_title, new_title)
    group_items = list(all_groups.items())

    if args.limit:
        group_items = group_items[: args.limit]
        print(f"[main] Limiting to {args.limit} group(s)")

    for idx, (shared_title, pages) in enumerate(group_items, 1):
        print(f"\n[main] Group {idx}/{len(group_items)}: {len(pages)} page(s) sharing title: {shared_title!r}")

        if args.dry_run:
            for page in pages:
                print(f"  [dry-run] Would generate new title for: {page['file_path']}")
            continue

        new_titles = generate_titles(pages)
        if new_titles is None:
            print(f"  [main] Skipping group (AI generation failed)")
            continue

        for page in pages:
            fp = page["file_path"]
            new_title = new_titles.get(fp)
            if not new_title:
                print(f"  [main] No title returned for: {fp}")
                continue

            old_title = page["title"]
            print(f"  {old_title!r}")
            print(f"  -> {new_title!r}")

            if update_title(fp, new_title):
                changed_files.append(fp)
                rel = os.path.relpath(fp, REPO_ROOT)
                mappings.append((rel, old_title, new_title))
            else:
                print(f"  [main] WARNING: Failed to write: {fp}")

    # ── Summary ───────────────────────────────────────────────────────────────
    print(f"\n[main] {'[dry-run] ' if args.dry_run else ''}Done: {len(changed_files)} file(s) updated")

    if args.dry_run or args.skip_pr or not changed_files:
        return

    # ── Create PR ─────────────────────────────────────────────────────────────
    pr_body = _build_pr_body(mappings)
    github_pr.run_pr_flow(
        REPO_ROOT,
        changed_files,
        branch_name=TITLE_BRANCH_NAME,
        pr_title=TITLE_PR_TITLE,
        pr_body=pr_body,
        commit_msg=_COMMIT_MSG,
    )


if __name__ == "__main__":
    main()
