#!/usr/bin/env python3
"""
Entry point: fix duplicate meta descriptions using SEMrush Site Audit data.

Full workflow:
    1. Pull duplicate meta description URLs from SEMrush Site Audit API
    2. Filter to /rules/ pages and map each URL to a repo file
    3. Read current frontmatter (title + seoDescription)
    4. Generate a unique replacement seoDescription using OpenAI
    5. Write the updated seoDescription back to the file (frontmatter only)
    6. Create a branch, commit, push, and open a GitHub PR (skipped with --dry-run or --skip-pr)

Usage:
    python run_duplicate_meta_fix.py [--dry-run] [--skip-pr] [--limit N] [--urls-file PATH]

Flags:
    --dry-run          Log what would change without writing any files (also skips PR)
    --skip-pr          Write files but do not create a branch or PR
    --limit N          Process at most N files (useful for testing a small batch)
    --urls-file PATH   Skip SEMrush and load URLs from a plain-text file instead
                       (one URL per line, lines starting with # are ignored).
                       Only OPENAI_API_KEY is required in this mode.

Required environment variables:
    SEMRUSH_API_KEY       SEMrush API key (not needed with --urls-file)
    SEMRUSH_PROJECT_ID    SEMrush project ID for ssw.com.au (not needed with --urls-file)
    OPENAI_API_KEY        OpenAI API key

Optional environment variables:
    REPO_ROOT             Absolute path to repo root
                          (defaults to two levels up from this script)
"""

import argparse
import os
import sys

# Make sibling modules importable when running from any working directory
_SCRIPT_DIR = os.path.dirname(os.path.realpath(__file__))
sys.path.insert(0, _SCRIPT_DIR)

from semrush_client import client_from_env, ISSUE_DUPLICATE_META
from map_urls_to_files import map_urls_to_files
from generate_seo_description import generate_description
from fix_duplicate_meta import read_frontmatter_fields, update_seo_description
import github_pr


def _build_pr_body(mappings: list[tuple[str, str, str]]) -> str:
    """mappings: list of (rel_file_path, old_description, new_description)"""
    def _safe(val: str) -> str:
        return val.replace("|", "\\|")

    rows = "\n".join(
        f"| `{rel}` | {_safe(old)} | {_safe(new)} |"
        for rel, old, new in mappings
    )
    return (
        f"Fixes duplicate `seoDescription` frontmatter on {len(mappings)} /rules page(s) flagged by "
        f"SEMrush Site Audit. Only frontmatter was modified — page body and all other fields are unchanged. "
        f"New descriptions were generated by AI.\n\n"
        f"| File | Old description | New description |\n"
        f"|------|-----------------|------------------|\n"
        f"{rows}\n\n"
        f"> AI-generated — human review required before merge.\n"
    )


def _parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Fix duplicate meta descriptions from SEMrush Site Audit data"
    )
    p.add_argument(
        "--dry-run",
        action="store_true",
        help="Log planned changes without writing any files",
    )
    p.add_argument(
        "--limit",
        type=int,
        default=0,
        metavar="N",
        help="Process at most N files (0 = no limit)",
    )
    p.add_argument(
        "--urls-file",
        metavar="PATH",
        help="Skip SEMrush: load URLs from a plain-text file (one per line)",
    )
    p.add_argument(
        "--list-issues",
        action="store_true",
        help="Print all issue types in the latest SEMrush snapshot and exit",
    )
    p.add_argument(
        "--skip-pr",
        action="store_true",
        help="Write files but skip branch creation and PR (useful for local testing)",
    )
    return p.parse_args()


def _load_urls_from_file(path: str) -> list[str]:
    with open(path, "r", encoding="utf-8") as f:
        lines = f.readlines()
    return [l.strip() for l in lines if l.strip() and not l.strip().startswith("#")]


def _get_repo_root() -> str:
    explicit = os.environ.get("REPO_ROOT", "")
    if explicit:
        return explicit
    # Default: scripts/semrush/ is two levels inside the repo root
    return os.path.abspath(os.path.join(_SCRIPT_DIR, "..", ".."))


def main() -> None:
    args = _parse_args()
    repo_root = _get_repo_root()

    print("=" * 60)
    print("SEMrush duplicate meta description fixer")
    print("=" * 60)
    if args.dry_run:
        print("MODE: DRY RUN — no files will be modified\n")
    elif args.skip_pr:
        print("MODE: SKIP PR — files will be written but no branch/PR will be created\n")
    print(f"Repo root : {repo_root}")
    if args.limit:
        print(f"Limit     : {args.limit} files\n")

    # ── --list-issues: discovery mode ────────────────────────────────────────
    if args.list_issues:
        semrush = client_from_env()
        print("\n── Fetching all issue types from latest SEMrush snapshot ──")
        issues = semrush.list_issues()
        if not issues:
            print("No issues returned. Check the raw response above.")
            return
        # Show raw structure of first item to help diagnose field names
        print(f"Raw structure of first issue item: {issues[0]}")
        print()
        # Print as a table sorted by count descending
        issues_sorted = sorted(
            issues,
            key=lambda x: x.get("count") or x.get("errorsCount") or x.get("errors_count") or 0,
            reverse=True,
        )
        count_key = next(
            (k for k in ["count", "errorsCount", "errors_count", "total"] if issues[0].get(k) is not None),
            None,
        )
        title_key = next(
            (k for k in ["title", "name", "description"] if issues[0].get(k) is not None),
            None,
        )
        print(f"{'Issue ID':<10} {'Count':>8}  Title")
        print("-" * 60)
        for iss in issues_sorted:
            iss_id = iss.get("id") or iss.get("issue_id") or str(iss)
            count  = iss.get(count_key, "?") if count_key else "?"
            title  = iss.get(title_key, "") if title_key else ""
            print(f"{str(iss_id):<10} {str(count):>8}  {title}")
        print(f"\nTotal issue types: {len(issues)}")
        print(f"\nCurrent ISSUE_DUPLICATE_META setting: '{ISSUE_DUPLICATE_META}'")
        print("(Duplicate meta descriptions is typically issue ID 15 in SEMrush)")
        return

    # ── Early duplicate PR guard (skip in dry-run / skip-pr modes) ──────────
    if not args.dry_run and not args.skip_pr and not args.list_issues:
        existing_pr = github_pr.check_open_pr(repo_root)
        if existing_pr:
            print(
                f"\n[run] An open PR for branch {github_pr.BRANCH_NAME!r} already exists:\n"
                f"[run]   {existing_pr}\n"
                f"[run] Exiting to avoid duplicate PRs. Close or merge that PR first."
            )
            return

    # ── Step 1: Fetch affected URLs (SEMrush or local file) ──────────────────
    if args.urls_file:
        print(f"\n── Step 1: Loading URLs from file: {args.urls_file} ──")
        urls = _load_urls_from_file(args.urls_file)
        print(f"[run] Loaded {len(urls)} URL(s)")
    else:
        print("\n── Step 1: Fetching duplicate meta description issues from SEMrush ──")
        semrush = client_from_env()
        try:
            urls = semrush.get_duplicate_meta_pages()
        except Exception as exc:
            print(f"ERROR: SEMrush API call failed: {exc}", file=sys.stderr)
            sys.exit(1)

    if not urls:
        print("No URLs to process. Nothing to do.")
        return

    # ── Step 2: Map URLs to repo files ───────────────────────────────────────
    print(f"\n── Step 2: Mapping {len(urls)} URL(s) to repo files ──")
    url_to_file = map_urls_to_files(urls, repo_root)

    if not url_to_file:
        print("No URLs could be mapped to files on disk. Exiting.")
        return

    if args.limit and args.limit > 0:
        url_to_file = dict(list(url_to_file.items())[: args.limit])
        print(f"[run] Limit applied — processing {len(url_to_file)} file(s)")

    # ── Steps 3–5: Generate descriptions and write changes ───────────────────
    total = len(url_to_file)
    print(f"\n── Steps 3–5: Generating + applying descriptions for {total} file(s) ──")

    used_descriptions: set[str] = set()
    changed_files: list[str] = []
    mappings: list[tuple[str, str, str]] = []  # (rel_path, old_desc, new_desc)
    counts = {"updated": 0, "skipped": 0, "failed": 0}

    for i, (url, file_path) in enumerate(url_to_file.items(), start=1):
        rel = os.path.relpath(file_path, repo_root)
        print(f"\n[{i}/{total}] {rel}")
        print(f"  url    : {url}")

        # Step 3: Read frontmatter
        fields = read_frontmatter_fields(file_path)
        if fields is None:
            print("  SKIP: could not parse frontmatter")
            counts["skipped"] += 1
            continue

        title = fields.get("title") or ""
        current_desc = fields.get("seoDescription") or ""
        file_content = fields.get("_content") or ""

        if not title:
            print("  SKIP: no title in frontmatter")
            counts["skipped"] += 1
            continue

        print(f"  title  : {title[:100]}")
        print(f"  current: {current_desc[:100]}")

        # Step 4: Generate new description
        new_desc = generate_description(
            title=title,
            current_desc=current_desc,
            file_content=file_content,
            used_descriptions=used_descriptions,
        )

        if new_desc is None:
            print("  SKIP: description generation returned nothing usable")
            counts["skipped"] += 1
            continue

        print(f"  new    : {new_desc}")
        print(f"  length : {len(new_desc)} chars")

        # Step 5: Write change
        if args.dry_run:
            print("  [DRY RUN] Would update seoDescription — no file written")
            used_descriptions.add(new_desc.lower().strip())
            mappings.append((rel, current_desc, new_desc))
            counts["updated"] += 1
        else:
            ok = update_seo_description(file_path, new_desc)
            if ok:
                used_descriptions.add(new_desc.lower().strip())
                changed_files.append(file_path)
                mappings.append((rel, current_desc, new_desc))
                counts["updated"] += 1
                print("  OK: seoDescription updated")
            else:
                counts["failed"] += 1
                print("  FAIL: could not update file (see above)")

    # ── Summary ──────────────────────────────────────────────────────────────
    print("\n" + "=" * 60)
    print("Summary")
    print("=" * 60)
    print(f"  Updated : {counts['updated']}")
    print(f"  Skipped : {counts['skipped']}")
    print(f"  Failed  : {counts['failed']}")

    if counts["updated"] > 0 and not args.dry_run:
        if args.skip_pr:
            print("""
Files written. Next steps (--skip-pr was set):
  1. Review diffs:
       git diff public/uploads/rules/

  2. Validate frontmatter:
       cd scripts/frontmatter-validator && npm install
       node frontmatter-validator.js '<comma-separated file paths>'

  3. Create branch and PR manually, or re-run without --skip-pr.
""")
        else:
            print("\n── Step 6: Creating branch, committing, and opening PR ──")
            github_pr.run_pr_flow(repo_root, changed_files, pr_body=_build_pr_body(mappings))


if __name__ == "__main__":
    main()
