---
seoDescription: Regularly auditing your Google Ads account ensures accurate click tracking and prevents overcharging by identifying effective campaigns.
type: rule
archivedreason:
title: SEM - Do you regularly audit your Google Ads account?
guid: 861c24ab-509c-496c-a2d2-d5895487847f
uri: regularly-audit-your-google-ads-account
created: 2014-10-13T19:10:27.0000000Z
authors:
  - title: Ulysses Maclaren
    url: https://ssw.com.au/people/ulysses-maclaren
related: []
redirects:
  - do-you-regularly-audit-your-google-adwords-account
  - sem-do-you-regularly-audit-your-google-ads-account
---

After learning about [the $90M fraud case settlement by Google](https://www.cbsnews.com/news/google-settles-fraud-case-for-90m), we put in place redirect files to keep track of the amount of clicks obtained from our Ads. Up until April 2006, we were led to believe that the amount of clicks Google were specifying was the number of clicks we were receiving. How wrong we were! After implementing the redirect files, we quickly learnt that the number of clicks of one of our campaigns was incorrect and we were being overcharged.

<!--endintro-->

By implementing redirect files, you can keep track of exactly how many clicks are being generated by your Ads. Hence, you can see which campaigns are more effective and just as importantly, keeping track of exactly how much you should be charged for this.
