name: Notify n8n of new rules

on:
  push:
    branches: [main]
    paths:
      - 'rules/**/rule.md'   # only runs when any rule file is touched

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: List brand-new rule files
        id: diff
        run: |
          ADDED=$(git diff --diff-filter=A --name-only \
                  ${{ github.event.before }} ${{ github.sha }} \
                  | grep -E '^rules/.+\.md$' || true)
          echo "files=$ADDED" >> "$GITHUB_OUTPUT"

      - name: Call n8n for each new rule
        if: steps.diff.outputs.files != ''
        env:
          WEBHOOK_URL: ${{ secrets.N8N_RULE_WEBHOOK }}
          run: |
            for f in ${{ steps.diff.outputs.files }}; do
              # jq -Rs '.' converts the file to a single JSON-escaped string
              CONTENT=$(jq -Rs '.' < "$f")
        
              curl -s -X POST "$WEBHOOK_URL" \
                   -H 'Content-Type: application/json' \
                   -d "{\"path\":\"$f\",\"commit\":\"${GITHUB_SHA}\",\"content\":${CONTENT}}"
            done
