name: Test CheckExtensionCase

on:
  pull_request:
    branches: [ main ]
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
          
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.4

      - name: check-image-extension-case
        run: |
          FILES=${{steps.file_changes.outputs.files_added}}

          if [ ${#FILES} -ge 3 ];
          then
              IFS=", " read -a myarray <<< $FILES

              for filename in "${myarray[@]}" 
              do
                  echo "Checking file: $filename"
                  fileExtension=$(echo "${filename##*.}" | sed 's/[]]//g')
                  lowercaseFileExtension=$(echo "$fileExtension" | tr '[:upper:]' '[:lower:]')
                  echo "File extension: $fileExtension"
                  echo "Lowercase file extension: $lowercaseFileExtension"
                  if [ $lowercaseFileExtension == 'gif' ] || \
                     [ $lowercaseFileExtension == 'svg' ] || \
                     [ $lowercaseFileExtension == 'png' ] || \
                     [ $lowercaseFileExtension == 'jpg' ] || \
                     [ $lowercaseFileExtension == 'jpeg' ]
                  then
                      if [ "$fileExtension" != "$lowercaseFileExtension" ];
                      then
                          echo "Error: Use lowercase file extensions"
                          exit 1
                      fi
                  fi
              done
          fi
